---
# file: openshift.yml
- import_playbook: openstack_cloud_facts.yml
- hosts: openshift
  gather_facts: false
  vars_files:
    - "group_vars/openstack"
  roles:
    - openshift
    - { role: 'waitforcomplete', when: wait_for_complete|bool }
