---
# file: roles/uninstall/tasks/main.yml
- name: Delete all instances
  os_server:
     state: absent
     cloud: "{{ os_project }}"
     name: "{{ inventory_hostname }}"
     delete_fip: yes
- name: Delete all port allocations
  os_port:
     state: absent
     cloud: "{{ os_project }}"
     name: "{{ inventory_hostname }}"
- name: Delete the router
  run_once: true
  os_router:
     cloud: "{{ os_project }}"
     state: absent
     name: "{{ router_name }}"
- name: Delete the subnet
  run_once: true
  os_subnet:
     cloud: "{{ os_project }}"
     state: absent
     name: "{{ subnet_name }}"
- name: Delete the network
  run_once: true
  os_network:
     cloud: "{{ os_project }}"
     state: absent
     name: "{{ network_name }}"
     project: "{{ project }}"
- name: Delete the user
  run_once: true
  os_user:
     cloud: "{{ os_admin }}"
     state: absent
     name: "{{ ospuser }}"
- name: Delete the project
  run_once: true
  os_project:
     cloud: "{{ os_admin }}"
     state: absent
     name: "{{ project }}"
- name: Delete master flavor
  run_once: true
  os_nova_flavor:
     state: absent
     cloud: "{{ os_admin }}"
     name: "{{ master_flavor_name }}"
  when: remove_image_and_flavors|bool
- name: Delete worker flavor
  os_nova_flavor:
     state: absent
     cloud: "{{ os_admin }}"
     name: "{{ worker_flavor_name }}"
  when: remove_image_and_flavors|bool
- name: Delete CoreOS image
  os_image:
     state: absent
     cloud: "{{ os_admin }}"
     name: "{{ coreos_image_name }}"
  when: remove_image_and_flavors|bool
