---
# file: roles/openstack/tasks/main.yml
- name: Create project
  os_project:
     state: present
     cloud: "{{ os_admin }}"
     name: "{{ project }}"
     description: OCP 4 UPI
     domain_id: "{{ user_domain }}"
     enabled: True
- name: Change project quota
  os_quota:
     cloud: "{{ os_admin }}"
     name: "{{ project }}"
     cores: 100
     ram: 120000
- name: Create user
  os_user:
     state: present
     cloud: "{{ os_admin }}"
     name: "{{ ospuser }}"
     password: "{{ osppassword }}"
     email: "{{ email }}"
     domain: "{{ user_domain }}"
     default_project: "{{ project }}"
- name: Associate role
  os_user_role:
     cloud: "{{ os_admin }}"
     user: "{{ ospuser }}"
     role: admin
     project: "{{ project }}"
- name: Associate role
  os_user_role:
     cloud: "{{ os_admin }}"
     user: "{{ ospuser }}"
     role: member
     project: "{{ project }}"
- name: Add keypair
  os_keypair:
     state: present
     cloud: "{{ os_project }}"
     name: "{{ ospuser }}"
     public_key_file: "{{ ssh_key }}"
- name: TCP Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_admin }}"
     security_group: default
     project: "{{ project }}"
     protocol: tcp
     remote_ip_prefix: 0.0.0.0/0
- name: UDP Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_admin }}"
     security_group: default
     project: "{{ project }}"
     protocol: udp
     remote_ip_prefix: 0.0.0.0/0
- name: ICMP Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_admin }}"
     security_group: default
     project: "{{ project }}"
     protocol: icmp
     remote_ip_prefix: 0.0.0.0/0
- name: SSH Security Group Rule
  os_security_group_rule:
     cloud: "{{ os_admin }}"
     security_group: default
     project: "{{ project }}"
     protocol: tcp
     port_range_min: 22
     port_range_max: 22
     remote_ip_prefix: 0.0.0.0/0
- name: Add network
  os_network:
     state: present
     cloud: "{{ os_admin }}"
     name: "{{ network_name }}"
     project: "{{ project }}"
     shared: no
     external: false
- name: Add subnet to network
  os_subnet:
     state: present
     cloud: "{{ os_admin }}"
     project: "{{ project }}"
     network_name: "{{ network_name }}"
     name: "{{ subnet_name }}"
     cidr: "{{ subnet }}{{ cidr }}"
     gateway_ip: "{{ gateway_ip }}"
     allocation_pool_start: "{{ allocation_pool_start }}"
     allocation_pool_end: "{{ allocation_pool_end }}"
     ip_version: 4
     dns_nameservers:
        - "{{ hostvars['api'].fixed_ip }}"
        - 10.10.11.2
        - 10.10.11.3
        - 10.10.11.4
- name: Create router for private and external routing
  os_router:
     state: present
     cloud: "{{ os_admin }}"
     name: "{{ router_name }}"
     project: "{{ project }}"
     network: public
     enable_snat: yes
     interfaces:
        - "{{ subnet_name }}"
